### PR TITLE
Migrate GB records from admin-xy

### PR DESCRIPTION
**Pull request by tomtaylor**
Some GB records have been hanging out in the XY repo, because of reasons related to the Great Migration. Move these over so they're hanging out in the right repo. See also https://github.com/whosonfirst-data/whosonfirst-data-admin-xy/pull/33.

### CODE REVIEW

**Comment by stepps00** [comment]
Changes look good! Thanks for pulling these records into the appropriate repo.

Minor nit, but not required to merge - is it possible to update the `wof:country` and `iso:country` property values for each of these records? Something like:

```
...
"iso:country":"GB",
...
"wof:country":"GB",
...
```

**Comment by tomtaylor** [comment]
Yes, let me follow up with that. It'll require re-exporting these records as they're not aligned with the current Golang exporter.

**Comment by tomtaylor** [comment]
All done.

**Review by stepps00 — APPROVED** [review]
LGTM

**Comment by stepps00** [comment]
Sure - approved and merging. Thanks @tomtaylor !

**Pull request merged**
