### PR TITLE
Multiple and Duplicate Geonames ID fixes for GB

### PR DESCRIPTION
**Pull request by vicchi**
4 WOF documents in this repo have a string with _two_ Geonames IDs, comma separated, either in `gn:id` or `geonames:id`.

In all cases these _smell_ incorrect based on examination and cross reference with Geonames, so ...

* London had two Geonames IDs, one for London (correctly) and one for the _City of London_ (incorrectly as this is a separate place in both WOF and GN)
* Letchworth Garden City had two Geonames IDs, one of which is deprecated in Geonames and automagically fast forwards
* Hucknall had two Geonames IDs, one for Hucknall (which is current) and a duplicate for Hucknall-under-Huthwaite which was Hucknall's name up until 1907 and it's been Hucknall ever since
* Bidford-on-Avon had two Geonames IDs, one of which was a duplicate for Bidford-on-avon (note the lowercase _avon_)

### CODE REVIEW

**Comment by vicchi** [comment]
Paging @stepps00 and @thisisaaronland, plus also @nvkelso as this is a precursor and unblocker to getting a local Spelunker and API set up so I can do what I first started out doing which is whosonfirst-data/whosonfirst-data#1871

**Comment by stepps00** [comment]
Thanks @vicchi - these changes look good to me, though the records will need to be run against the `wof-exportify` tool ([Go version](https://github.com/whosonfirst/go-whosonfirst-export), [Python version](https://github.com/whosonfirst/py-mapzen-whosonfirst-export)). Is this something you'd be willing to handle here? If not, I can merge and follow up with a new commit to exportify the records.

This is tool validates and changes and updates the `wof:lastmodified` date, which is helpful to know when records were last edited.

**Comment by nvkelso** [comment]
LGTM modulo Stephen's point about exportify-ing (to update the modified timestamps and sanity check the JSON formatting). Thanks!

**Comment by thisisaaronland** [comment]
@vicchi this is probably not an issue since you're already neck-deep in the `py-mz-wof` packages but FYI this exists for making "exportifying" a little easier for people who aren't:

https://github.com/whosonfirst/docker-whosonfirst-exportify

**Comment by vicchi** [comment]
Ah ... wasn't aware of the need for `wof-exportify` though that now makes perfect sense after reading the above. Will do that shortly and commit/push to my forked repo's branch.

**Comment by vicchi** [comment]
Sigh ... `pip` post version 1.6 with your dropping `--process-dependency-links` ... I hate you

```
$ wof-exportify --help
Traceback (most recent call last):
  File "/var/whosonfirst/p2env/bin/wof-exportify", line 10, in <module>
    import mapzen.whosonfirst.export
  File "/var/whosonfirst/p2env/lib/python2.7/site-packages/mapzen/whosonfirst/export/__init__.py", line 16, in <module>
    import edtf
ImportError: No module named edtf
```

@stepps00 But now all exportified and ready for re-review

**Pull request merged**
